# Generated by Django 4.1.3 on 2022-12-04 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MatchApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sciendermatch',
            old_name='user2',
            new_name='from_user',
        ),
        migrations.RenameField(
            model_name='sciendermatch',
            old_name='user1',
            new_name='to_user',
        ),
    ]
