# Generated by Django 4.1.3 on 2022-11-22 04:15

import ChatApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienderchat',
            name='background',
            field=models.ImageField(default=ChatApp.models.backgroundDefaultImage, upload_to=ChatApp.models.backgroundUploadPath),
        ),
    ]
