# Generated by Django 4.1.3 on 2022-11-22 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scienderuser',
            name='status',
            field=models.CharField(choices=[('Free', 'Свободен'), ('Working', 'В работе'), ('Seeking team', 'В поиске команды'), ('Seeking project', 'В поиске проекта')], default='Free', max_length=255),
        ),
    ]
