# Generated by Django 4.1.3 on 2022-11-21 12:06

import ProjectApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CoreApp', '0001_initial'),
        ('AuthApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScienderProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField()),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Ready', 'Завершён'), ('Working', 'В работе'), ('Seeking team', 'Набор участников')], default='Seeking team', max_length=255)),
                ('image', models.ImageField(default=ProjectApp.models.projectDefaultImage, upload_to=ProjectApp.models.projectUploadPath)),
                ('interests', models.ManyToManyField(blank=True, related_name='interests', to='CoreApp.scienceinterests')),
                ('team', models.ManyToManyField(blank=True, related_name='team', to='AuthApp.scienderuser')),
                ('tutor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='AuthApp.scienderuser')),
            ],
        ),
    ]
